Module7 task1
htmlacademy-ecmascript/2298777-big-trip-20 pull request #12
Opened 2023-05-28 10:04 UTC by PapicBorovoi

2023-05-30 13:38 UTC, rgusseinov requested changes
Привет!

Проверил ДЗ по 7-му модулю.
Круто, теперь данные удаляются и добавляются.
Но нужно немного доработать, заметил некоторые проблемные участки.

1. Запрос в DOM напрямую не делаем.
document.querySelector('.trip-main__event-add-btn').
Нужно создать компонент для новой кнопки и туда передать обработчик клика, по аналогии с др. компонентами
В WindowPresenter, метод handleAddNewPointClick тоже обращается к DOM напрямую

2. В Filter presenter в конструкторе забыл поставить this перед filterModel и pointsModel для addObserver

3. Если удалить все точки маршрута и добавить новый, то сообщение о создании новой точки сохраняется
http://joxi.ru/J2bNZGMs0QYnp2

4. При добавлении новой точки маршрута, то появляется ошибка. Если выбрать тип ресторан и destination paris
window-presenter.js:106 Uncaught TypeError: Cannot read properties of undefined (reading 'offers')
    at window-presenter.js:106:86
    at Array.forEach (<anonymous>)
    at getPrice (window-presenter.js:105:19)

Как исправишь отправляй на проверку.
Удачи!

2023-05-31 05:55 UTC, rgusseinov commented
> Привет!
> 
> Проверил ДЗ по 7-му модулю. Круто, теперь данные удаляются и добавляются. Но нужно немного доработать, заметил некоторые проблемные участки.
> 
> 1. Запрос в DOM напрямую не делаем.
>    document.querySelector('.trip-main__event-add-btn').
>    Нужно создать компонент для новой кнопки и туда передать обработчик клика, по аналогии с др. компонентами
>    В WindowPresenter, метод handleAddNewPointClick тоже обращается к DOM напрямую
> 2. В Filter presenter в конструкторе забыл поставить this перед filterModel и pointsModel для addObserver
> 3. Если удалить все точки маршрута и добавить новый, то сообщение о создании новой точки сохраняется
>    http://joxi.ru/J2bNZGMs0QYnp2
> 4. При добавлении новой точки маршрута, то появляется ошибка. Если выбрать тип ресторан и destination paris
>    window-presenter.js:106 Uncaught TypeError: Cannot read properties of undefined (reading 'offers')
>    at window-presenter.js:106:86
>    at Array.forEach ()
>    at getPrice (window-presenter.js:105:19)
> 
> Как исправишь отправляй на проверку. Удачи!

Отлично, здесь все исправлено.
Молодец!

2023-05-31 05:56 UTC, rgusseinov requested changes
Привет!

Проверил, по пред. пунктам все хорошо.
Остались два момента, которые надо поправить.

1. Если из фильтра future например удалить все точки, то соответствующая надпись не выходит.  «There are no future events now».

2. По ТЗ не должно быть два открытых форм одновременно (создание точки и редактирование точки)
http://joxi.ru/eAO0yKpF9LEBer

Удачи и исправлении.
Если будут вопросы - пиши.

2023-05-31 06:58 UTC, PapicBorovoi commented
Дополнительно исправил выбор дат и обработчики на esc.

2023-06-01 03:13 UTC, rgusseinov commented
> Привет!
> 
> Проверил, по пред. пунктам все хорошо. Остались два момента, которые надо поправить.
> 
> 1. Если из фильтра future например удалить все точки, то соответствующая надпись не выходит.  «There are no future events now».
> 2. По ТЗ не должно быть два открытых форм одновременно (создание точки и редактирование точки)
>    http://joxi.ru/eAO0yKpF9LEBer
> 
> Удачи и исправлении. Если будут вопросы - пиши.

Проверил.
Теперь надпись выходит правильная для каждого типа фильтра.
И одна форма только может быть открыта.
Отлично

2023-06-01 03:14 UTC, rgusseinov approved these changes
Привет!

Проверил и оставил комментарии.
Движемся дальше.

2023-06-01 03:14 UTC, merged