+Динамические данные в point-view.
htmlacademy-ecmascript/2298777-big-trip-20 pull request #4
Opened 2023-04-29 17:02 UTC by PapicBorovoi

2023-04-30 18:20 UTC, rgusseinov requested changes
Привет!

Отлично,  данные беруется из моков и интерфейс уже начинает оживать.
Проверил ДЗ. 
Выделил некоторые пункты, которые надо исправить.

- В моках id офферов нужно сделать целочисленными.
- Скорее не Icons, а Types - это типы маршрута. Они еще нам понадобятся
- Кажется ошибка в названии функции createEventOfferSelecetor. 

Пока все. Исправляй и высылай на проверку.

2023-05-01 07:54 UTC, PapicBorovoi commented
Я сделал id целочисленными, но не уверен что это правильно. В схеме офферов id приходят в виде string.
<img width="980" alt="image" src="https://user-images.githubusercontent.com/118468279/235425515-013492da-446b-4df3-a013-635a862c95ca.png">

2023-05-02 07:02 UTC, rgusseinov approved these changes
Привет!

Отлично. Пункты по комментариям исправлены.

2023-05-02 07:02 UTC, merged

2023-05-02 07:46 UTC, rgusseinov commented
> Я сделал id целочисленными, но не уверен что это правильно. В схеме офферов id приходят в виде string. <img alt="image" width="980" src="https://user-images.githubusercontent.com/118468279/235425515-013492da-446b-4df3-a013-635a862c95ca.png">

Всегда ID были целыми.
![image](https://user-images.githubusercontent.com/75318149/235608905-df14416f-5dd7-4d52-bb7e-2c5c771d12b8.png)

Я проверю. Если поменялось что-нибудь я тебе скажу.