Module5 task1
htmlacademy-ecmascript/2298777-big-trip-20 pull request #7
Opened 2023-05-09 16:35 UTC by PapicBorovoi

2023-05-11 04:55 UTC, rgusseinov requested changes
Привет!

Проверил ДЗ, в принципе все работает, но нужно поменять структуру презенторов чтобы в дальнейшем было проще управлять карточками и фильтрами.

Ниже указал ключевые моменты, которые надо поправить. В целом, у тебя логика ListPresenter уехала в ListElementPresenter - это нужно исправить.

**Главный презентер:**

1. Нужно перенести коллекцию презентеров #listElements = new Map() в ListPresenter. Экземпляр презентера нужно создавать не внутри конструктора ListPresenter, а в его методе init. Т.е в цикле(от 1 и до всех точек) создаем экземпляр презентера точки и кладем их в коллекцию listElements.
Чтобы потом мы могли обращаться к презентеру определенной точки маршрута и вызвать у него какой-нибудь метод, например открытие формы редактирования.

Для упрощение можно сделать так: В методе init презентера ListPresenter вызываем метод
1.1. this.#renderPoints(); // Названия я показываю как пример, ты можешь написать свои, типа renderListElements

  #renderPoints() {
    for (let i = 0; i < this.#points.length; i++) {
      this.#renderPoint(this.#points[i]);
    }
  }


1.2. Внури renderPoint создаем экземпляр презентера для каждой точки

  #renderPoint(point) {
    const pointPresenter = new PointPresenter({
      pointListContainer: // Передаем DOM элемент
      onDataChange: this.#handlePointChange,
      onModeChange: this.#handleModeChange
    });

    pointPresenter.init(point); // Здесь передаем точку маршрута point
    this.#pointPresenters.set(point.id, pointPresenter); // Ложим каждый презентер точки в массив
  }

1.3. В методах handlePointChange и handleModeChange будем обновлять определенные точки при нажатии на рекдактировать или звездочку
Пример:

  #handlePointChange = (updatedPoint) => {
    this.#points = updateItem(this.#points, updatedPoint);
    this.#pointPresenters.get(updatedPoint.id).init(updatedPoint);
  };

  #handleModeChange = () => {
    this.#pointPresenters.forEach((presenter) => presenter.resetView());
  };


**Презентер точки:**

2. Как указано выше в примере, в конструктор презентера PointPresenter, нужно передать обработчики:
onDataChange и onModeChange - это нужно чтобы мы могли управлять например всеми карточками или менять состояние фильтра.


2.1 Внутри обработчика onEditPointButtonClick не забываем вызвать метод this.#handleDataChange(point);

2.2 Также нужног поменять статус isFavorite

#handleFavoriteClick = () => {
	this.#handleDataChange({ ...this.#point, isFavorite: !this.#point.isFavorite });
};

2.3 Нужно реализовать метод resetView сброса формы с режима редактирования на списочный вид. Для этого надо будет объявить объект Mode, как показывали на лекции.

Если будут вопросы - пиши, не стесняйся )
Удачи!

2023-05-11 16:19 UTC, PapicBorovoi commented
Было достаточно тяжело перейти от одного решения к абсолютно другому, но вроде получилось)

2023-05-12 15:34 UTC, rgusseinov requested changes
Привет!

Круто, молодец что подправил, теперь получше.
Оставил комментарии под пунктами, которые нужно исправить.
Сейчас мы исправим все что необходимо и дальше по этой схеме будет легче дорабатывать.

Как исправишь, высылай на проверку.
Жду.

2023-05-12 15:34 UTC, rgusseinov commented on src/presenter/list-presenter.js
> +  renderPoints({points = this.#points, destinations = this.#destinations, offers = this.#offers} = {}) {
Здесь не нужны параметры, они будут в методе init

2023-05-12 15:34 UTC, rgusseinov commented on src/presenter/list-presenter.js
> +        point: points[i],
перенести в point.init

2023-05-12 15:34 UTC, rgusseinov commented on src/presenter/list-presenter.js
> +        destination: destinations[i],
Тоже

2023-05-12 15:34 UTC, rgusseinov commented on src/presenter/list-presenter.js
> +        offers: offers[i],
Тоже

2023-05-12 15:34 UTC, rgusseinov commented on src/presenter/list-presenter.js
> +      point.init({});
Сюда будем передавать точку и this.destinations, this.offers

2023-05-12 15:34 UTC, rgusseinov commented on src/presenter/point-presenter.js
> +  init({point = this.#point, destination = this.#destination, offers = this.#offers}) {
Параметры убираем

2023-05-12 15:34 UTC, rgusseinov commented on src/presenter/point-presenter.js
> +    this.#point = point;
Переносим в метод init в самое начало

2023-05-12 15:34 UTC, rgusseinov commented on src/presenter/point-presenter.js
> +  constructor({pointContainer, onModeChange, onPointChange, point, destination, offers}) {
Кажется  onModeChange и onPointChange местами перепутаны

2023-05-12 15:55 UTC, rgusseinov requested changes
Юрий, добавил еще правок

2023-05-12 15:55 UTC, rgusseinov commented on src/presenter/point-presenter.js
> +    const onEditPointButtonClick = () => {
Обработчик должен быть снаружи метода init

2023-05-12 15:55 UTC, rgusseinov commented on src/presenter/point-presenter.js
> +    const onPointButtonClick = () => {
Этот обработчик тоже должен быть снаружи метода init

2023-05-12 15:55 UTC, rgusseinov commented on src/presenter/point-presenter.js
> +    const onFavoriteButtonClick = () => {
Обработчик должен быть снаружи метода init

2023-05-12 15:55 UTC, rgusseinov commented on src/presenter/point-presenter.js
> +      this.#onPointChange({...point, isFavorite: !point.isFavorite});
Можно будет обратиться через  this.#point

2023-05-13 11:26 UTC, rgusseinov approved these changes
Привет!

Проверил ДЗ, по пунктам, теперь все в порядке. Молодец.
Отлично.

Жду след. ДЗ на проверку.
Удачи!

2023-05-13 11:28 UTC, merged