Module6 task1
htmlacademy-ecmascript/2298777-big-trip-20 pull request #9
Opened 2023-05-17 11:27 UTC by PapicBorovoi

2023-05-18 12:45 UTC, rgusseinov requested changes
Привет!

Проверил по части формы редактирования точки. Классно, уже начинает оживать наша форму.
Но, нужно внести некоторые корректировки.

1. При открытие карточки точки(форма редактирования), offer'ы должны отображаться все относящиеся к этому типу. Но выбраны(выделены) должны быть те которые у нас в точке point.offers. Т.е. чтобы сразу было видно сколько всего offer'ов и какие из них выбраны. http://joxi.ru/l2Znjyauz97jJ2
2.  При изменении пункта назначения(destination) текст меняется, но картинки не отображаются, нужно чтобы картинки тоже подтягивались. http://joxi.ru/brRENRVf7jOqjA
3.  В компоненте EditPointView лучше завести два статических метода parsePointToState и parseStateToPoint чтобы было проще управлять стейтом поинтов и не приложись дублировать код. Как показывали на ретро.

Пока все, как исправишь отправляй на проверку.
Если будут вопросы - пиши)

2023-05-18 18:55 UTC, PapicBorovoi commented
Исправил 1 и 2 пункт, но не понял где здесь в коде применить parsePointToState и parseStateToPoint, вроде доп. информация для стейта здесь не нужна.

2023-05-20 12:27 UTC, rgusseinov requested changes
Привет!

Проверил ДЗ.
Заметил несколько неточностей, давай их исправим чтобы потом было проще.

Пункты на исправление:
- В updateElement мы передаем только те данные которые поменяли, без point: {} и destination:
Иначе при отправке формы на сервер, данные не сохранятся корректно.

Например если меняем тип точки c taxi на train, то будет это выглядеть так:
      this.updateElement({
        type: 'train',
        offers:[]
      });
	  
	  Если меняем destionation, то так:
	  
	  this.updateElement({
        destination: ''
      });
	  
	  Т.е. внутри updateElement наша точка уже развернута и нужно просто закинуть туда обновленные данные
Повторюсь. Туда не нужно передавать allOfers, destinations итд. Только поля по точке
	 
- Во вью файле в  handleOfferChange не нужно вызывать метод updateElement, поскольку он перерисовывает
компонент edit view. Нам нужно просто обновить state, а именно офферы.

- В методе handleOfferChange офферы неправильно обрабатываются.
Нужно обрабатывать не массив this._state.allOfers, а this._state.offers
Получаем id нажатого offer'а, далее в массиве this._state.offers находим его и удаляем.
Не забудь условие по добавлению нового оффера. В случае если мы ходим выбрать новый оффер.

- По поводу parsePointToState и parseStateToPoint. Их удобно применять когда например конструкторе нашу точку разворачиваем и ложем в стейт.  
А когда будем отправлять данные на сервер, то стейт превращаем в точку через функцию parseStateToPoint.
Вот так: {id: 1, basePrice: 100, .....}
Это по сути это простые и для удобства функции. На ретро показывали как их объявить и использовать.

- В handlePriceChange цену меняем только в стейте, поскольку она не должна влиять на перерисовку

Если будут вопросы, смело пиши.
Удачи!

2023-05-20 12:31 UTC, rgusseinov commented
> Исправил 1 и 2 пункт, но не понял где здесь в коде применить parsePointToState и parseStateToPoint, вроде доп. информация для стейта здесь не нужна.

2023-05-20 12:31 UTC, closed without merging